nodes:
  master:
    ip: "100.109.171.107"
    port: 8000
    n_threads: 10
    ram_gb: 16
    role: "master"
  worker:
    ip: "100.98.33.46"
    port: 8001
    n_threads: 2
    ram_gb: 4
    role: "worker"